// This file was auto-generated by ML.NET Model Builder. 

using System;
using NeuralNetworkSample2021ML.Model;

namespace NeuralNetworkSample2021ML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Latitude = 35.9948F,
                Longitude = 136.1441F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual CorrectValue with predicted CorrectValue from sample data...\n\n");
            Console.WriteLine($"Latitude: {sampleData.Latitude}");
            Console.WriteLine($"Longitude: {sampleData.Longitude}");
            Console.WriteLine($"\n\nPredicted CorrectValue value {predictionResult.Prediction} \nPredicted CorrectValue scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
