// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace NeuralNetworkSample2021ML.Model
{
    public class ModelInput
    {
        [ColumnName("Latitude"), LoadColumn(0)]
        public float Latitude { get; set; }


        [ColumnName("Longitude"), LoadColumn(1)]
        public float Longitude { get; set; }


        [ColumnName("CorrectValue"), LoadColumn(2)]
        public float CorrectValue { get; set; }


    }
}
